### ISSUE TITLE
Typo in variable names 

### ISSUE THREAD

**Issue by wd60622** [timvink/mkdocs-git-revision-date-localized-plugin#104]
A few of the variable names here are written in kebab case instead of snake case
https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/master/docs/available-variables.md

This is only an error in the docs but will cause an error if attempting to use

**Comment by timvink** [comment]
Haha why did I not know about kebab-case 🍢 , great name.

Thanks for noticing and reporting!

**Comment by wd60622** [comment]
Ha. Wish I could take credit but heard it somewhere. Think it is standard. 

I can take a stab at the PR if you'd like
