### ISSUE TITLE
The plugin breaks with the last mkdocs docker image

### ISSUE THREAD

**Issue by Emmanuel-Messulam** [timvink/mkdocs-git-revision-date-localized-plugin#106]
With `squidfunk/mkdocs-material:8.2.1` the page works fine but with `squidfunk/mkdocs-material:8.5.11` it breaks with a lot of:
```bash
WARNING  -  [git-revision-date-localized-plugin] Unable to read git logs of '...'. Is git log readable? Option 'fallback_to_build_date' set to 'true': Falling back to build date
```

**Comment by tibitoth** [comment]
I have the same error, and the following workaround did **not** work

```
RUN git config --global --add safe.directory /github/workspace
```

**Comment by Emmanuel-Messulam** [comment]
> I have the same error and the following workaround did **not** work
> 
> ```
> RUN git config --global --add safe.directory /github/workspace
> ```

That is the solution to another issue.

**Comment by Emmanuel-Messulam** [comment]
Updating to `squidfunk/mkdocs-material:9.0.3` works.
