### ISSUE TITLE
The plugin breaks with squidfunk/mkdocs-material:9.0.3

### ISSUE THREAD

**Issue by Emmanuel-Messulam** [timvink/mkdocs-git-revision-date-localized-plugin#107]
I get a `fatal: detected dubious ownership in repository at '/site'`.

Workaround:
```
RUN git config --global --add safe.directory '/site'
```

**Comment by timvink** [comment]
Thanks for letting me know. Solution contributed back to `mkdocs-material` in https://github.com/squidfunk/mkdocs-material/pull/4876, referencing this issue
