### ISSUE TITLE
Timeago setting results in incorrect items being added to extra_javascript

### ISSUE THREAD

**Issue by nint8835** [timvink/mkdocs-git-revision-date-localized-plugin#117]
As of mkdocs 1.5, [`extra_javascript` after the config is no longer an array of strings](https://www.mkdocs.org/user-guide/configuration/#extra_javascript), but is instead a list of [`ExtraScriptValue`](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/config/config_options.py#L925).

Mkdocs appears to have fallback logic that handles the strings this plugin inserts into the list, but it can cause issues for plugins that assume all objects in the list are of the expected type (such as Material for Mkdocs, which is how I encountered this https://github.com/squidfunk/mkdocs-material/issues/5778)

**Comment by oprypin** [comment]
I came to a conclusion that we'll never get rid of strings being put into `extra_javascript`, so instead it will be officially embraced. https://github.com/mkdocs/mkdocs/pull/3324
MkDocs itself will now also normally put strings into the list.
So perhaps nothing to do here.

**Comment by timvink** [comment]
Late reply, but thanks both! 

Indeed currently using strings in `extra_javascript`:

https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/6150fad41a83abbf7500cf9c75696c5193532305/mkdocs_git_revision_date_localized_plugin/plugin.py#L124-L132
