### ISSUE TITLE
DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version

### ISSUE THREAD

**Issue by natakazakova** [timvink/mkdocs-git-revision-date-localized-plugin#121]
Hi! Can you please update the usage of `utcfromtimestamp`? I have about 70+ info warnings in my logs. It became difficult to search warnings and errors in log.

```
DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  File "/usr/local/lib/python3.12/site-packages/mkdocs_git_revision_date_localized_plugin/util.py", line 204, in get_date_formats_for_timestamp
    date_formats = self._date_formats(
  File "/usr/local/lib/python3.12/site-packages/mkdocs_git_revision_date_localized_plugin/util.py", line 66, in _date_formats
    utc_revision_date = datetime.utcfromtimestamp(int(unix_timestamp))
```

**Comment by timvink** [comment]
Python 3.12 is not officially supported yet, but it would be an improvement.

> [datetime.datetime](https://docs.python.org/3.12/library/datetime.html#datetime.datetime)’s [utcnow()](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.utcnow) and [utcfromtimestamp()](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.utcfromtimestamp) are deprecated and will be removed in a future version. Instead, use timezone-aware objects to represent datetimes in UTC: respectively, call [now()](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.now) and [fromtimestamp()](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.fromtimestamp) with the tz parameter set to [datetime.UTC](https://docs.python.org/3.12/library/datetime.html#datetime.UTC). (Contributed by Paul Ganssle in [gh-103857](https://github.com/python/cpython/issues/103857).)
