### ISSUE TITLE
1.2.3 breaks integration with Material for MkDocs

### ISSUE THREAD

**Issue by squidfunk** [timvink/mkdocs-git-revision-date-localized-plugin#127]
Sadly, the latest release breaks the integration with Material for MkDocs. I'm not sure what we need to do here other than to tell our users to downgrade to 1.2.2, because until now, [it is completely unclear how a migration path should look](https://github.com/mkdocs/mkdocs/issues/3357#issuecomment-1925004409). I might be missing something, but the maintainers of MkDocs have yet not provided instructions how to make themes and plugins downward compatible. It is the exact reason I'm raising awareness

Downstream issue: https://github.com/squidfunk/mkdocs-material/issues/6734

**Comment by timvink** [comment]
Thanks for letting me know. Will revert and make a new release soon

**Comment by oprypin** [comment]
@timvink Sorry about the bad change, this was supposed to be about forwards compatibility but instead made a separate breakage. Could I try to make the change again but correctly this time 🥺
https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/pull/126#discussion_r1477012765

**Comment by timvink** [comment]
No worries, it's on me, I should have tested more.

Let's try again 👍

**Comment by timvink** [comment]
It's released

**Comment by oprypin** [comment]
> Let's try again 👍

Thanks you.  The reland is ready for your consideration
https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/pull/128
