### ISSUE TITLE
Detach from fork tree

### ISSUE THREAD

**Issue by RDIL** [timvink/mkdocs-git-revision-date-localized-plugin#13]
Since this repository is essentially different from the original, I suggest you contact GitHub support and request for it to be detached as a fork, just so the GH UI doesn’t get confused.

**Comment by timvink** [comment]
I agree, by now most code has been replaced. Will pick this up!

**Comment by RDIL** [comment]
Cool.  Support should take care of it within 48 hours or so, I'll close this once its done.

**Comment by timvink** [comment]
Done!
