### ISSUE TITLE
DeprecationWarning when using Mldocs Material 9.5.20 and Mkdocs 1.60

### ISSUE THREAD

**Issue by HotCakeX** [timvink/mkdocs-git-revision-date-localized-plugin#133]
Hi, i see the warning message when I try to serve or build my documentation website

![image](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/assets/118815227/d2c8dc31-b006-4043-8bad-4aa864ad4834)

I reported it to Mkdocs material but they [said](https://github.com/squidfunk/mkdocs-material/issues/7119) i should report it here

**Comment by timvink** [comment]
Thanks. It's already been fixed on the main branch, will make a new release soon

**Comment by HotCakeX** [comment]
Thank you! 🙏

**Comment by lucasmior-hp** [comment]
What is the bugfix version? v1.2.5 ?

**Comment by timvink** [comment]
New release just published to pypi: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/releases/tag/v1.2.5
