### ISSUE TITLE
The creation date of the date plug-in seems to be incorrectly displayed 

### ISSUE THREAD

**Issue by W1ndys** [timvink/mkdocs-git-revision-date-localized-plugin#134]
Just like the question I asked [here](https://github.com/squidfunk/mkdocs-material/discussions/7161#/discussioncomment-9349167)

My Git commit record incorrectly shows that the history of some files is messed up

And the official community members of Mkdocs-material have given some [possibly feasible solutions](https://github.com/squidfunk/mkdocs-material/discussions/7161#discussioncomment-9344698)

I hope the plugin official can fix this error

I'd be grateful for any help
best wishes

**Comment by timvink** [comment]
Todo:

- Add new option to use `--follow` in git for creation date. Make sure to add referecnes to the git bug it addresses..

**Comment by timvink** [comment]
This plugin now uses `git --follow` by default, and has a new option to disable using `--follow`. 

See the release notes: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/releases/tag/v1.3.0
