### ISSUE TITLE
When building MkDocs with GitHub Actions, some warnings occured.

### ISSUE THREAD

**Issue by jygzyc** [timvink/mkdocs-git-revision-date-localized-plugin#136]
After running `mkdocs gh-deploy --force`, the warning information is as follows:

```
WARNING:root:
                [git-revision-date-localized-plugin] Running on bitbucket pipelines might lead to wrong
                Git revision dates due to a shallow git fetch depth.

                Try setting "clone: depth" to "full" in your pipeline
                (see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
                and search 'depth').
```

[GitHub Actions link ](https://github.com/jygzyc/notes/actions/runs/9258370368/job/25468313430)

**Comment by timvink** [comment]
Ha yeah you're not running on bitbucket. Thanks for creating the issue

**Comment by jygzyc** [comment]
> Ha yeah you're not running on bitbucket. Thanks for creating the issue

I happened to discover this issue while checking the GitHub Actions workflow, and I appreciate your handling of it.
