### ISSUE TITLE
Created always shows Last update - GitHub Pages using custom domain

### ISSUE THREAD

**Issue by avanbremen** [timvink/mkdocs-git-revision-date-localized-plugin#139]
Hi Tim, thanks for creating a great plugin!

We are using `git-revision-date-localized` on [our site](https://developer.zorgapis.nl/), however I noticed that 'Created' is always the same as 'Last update' after deploying to GitHub Pages. Note that we are using a custom domain (`CNAME` in the `docs` folder of our repository), perhaps that might be a factor here.

When running `mkdocs serve`, Last update and Created are correct on localhost.

Kind regards and all the best,
Arjan

**Comment by timvink** [comment]
By default CI systems do a shallow clone, instead of cloning the entire history.

You need to update your CI settings. See the note on build systems in the docs: https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/index.html

**Comment by avanbremen** [comment]
Thanks! Issue closed.
