### ISSUE TITLE
Option to ignore commits about move operations

### ISSUE THREAD

**Issue by skywarth** [timvink/mkdocs-git-revision-date-localized-plugin#147]
Hi there,

I just got started with using this plugin but ran into something which might be worth considering as a future. So recently I moved all my md files into a singular folder, and committed like so, hence the last change date of all my notes are pointing to that date, which is sub optimal because it is not an actual change, just a move operation. So how about an option to disregards last commit if it is a move operation, and doesn't contain any actual changes in the file itself? 

Here's an example scenario:
- Date: 13/01/2002, file moved (ignore)
- Date 05/01/2002, file moved (ignore)
- Date: 04:/01/2002, nominal commit, some change in the file (use this)
- Date: 01:/01/2002, nominal commit, some change in the file (not the latest)

Just a thought: move operations can be determined if file contents are identical per hash. 

This feature could come in handy, what do you think?

If it is a considerable feature, I might try to take a crack at it.

Thank you

**Comment by timvink** [comment]
Hee, that's a good one!

I think we can add that by adding a diff filter "r". See  
https://stackoverflow.com/questions/15130597/git-log-exclude-renames

It should be added here:

https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/3f39e6558213de330b4fbb5e6473aaf95a07713c/src/mkdocs_git_revision_date_localized_plugin/util.py#L96

And here's an example of how to add the diff filter argument, as we already use it for the creation date.

https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/3f39e6558213de330b4fbb5e6473aaf95a07713c/src/mkdocs_git_revision_date_localized_plugin/util.py#L86

Would appreciate a PR!

**Comment by timvink** [comment]
Released: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/releases/tag/v1.3.0
