### ISSUE TITLE
Py2/3 issue with MkDocs

### ISSUE THREAD

**Issue by uliska** [timvink/mkdocs-git-revision-date-localized-plugin#15]
I'm stumbling over Python2/3 with MkDocs and want to ask you @timvink about your idea to go forward.

[Context/situation:]

I had installed `mkdocs` through `pip3` giving me version `1.04`.
Since then (i.e. on current master)) The `config_options` module includes the `Choice` type (
https://github.com/mkdocs/mkdocs/blob/c9032bd6bfde09ead2f4f879e85590d7cd6e68a6/mkdocs/config/config_options.py#L160-L186) which is exactly what I'd want to use for the `aggregate_authors_on` option discussed in https://github.com/timvink/mkdocs-git-authors-plugin/pull/4#issuecomment-591345656 .

Consequentially Python3 balked at importing `config_options.Choice`, which is not present in MkDocs 1.04.

When I switched MkDocs to use current master `git-revision-date-localized-plugin` failed to import `string_types` from `mkdocs.utils`.

Further investigation reveals that MkDocs dropped Python2 support in https://github.com/openlilylib-resources/mkdocs/commit/c9032bd6bfde09ead2f4f879e85590d7cd6e68a6, removing (the need for) `string_types`.

That means that this plugin will break with the next MkDocs release. I suggest you take the opportunity and drop support for Python2 as well.

Until I hear from you I will stop work on the aggregation option. But I do need it. As you can see here it *does* make a difference when the name is identical but not the email ...

![grafik](https://user-images.githubusercontent.com/1812148/75444035-ec0a8180-5962-11ea-938f-99e8d41662aa.png)

... and I know this case happens all the time, especially with longer-running projects.

**Comment by timvink** [comment]
@uliska Thanks for the investigation. And nice to collaborate with you on the plugins! 

I'm OK with dropping python 2 support (`setup.py` actually mentions `python_requires='>=3.4'` but prob could be lower..

We can replace `string_types` with `str`, please see issue and my commit in https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/8

Does this solve the issue?

**Comment by uliska** [comment]
> I'm OK with dropping python 2 support (setup.py actually mentions python_requires='>=3.4' but prob could be lower.

Well, MkDocs requires Python >=3.5, so I'd actually *increase* to that.

> We can replace string_types with str, please see issue and my commit in #8
>
> Does this solve the issue?

Yes it does, and I'm not sure why I didn't notice. Probably I installed that plugin from PyPi very shortly before that release and didn't realize that you have to manually update it.

I'll close *this* issue and open a separate one for the Python 2 issue.

**Comment by timvink** [comment]
Sounds good. 

Also updated `setup.py` to require python>=3.5

**Comment by timvink** [comment]
> I'll close this issue and open a separate one for the Python 2 issue.

Is there still an issue with python 2? Can you elaborate?

**Comment by timvink** [comment]
Closing this issue for now, I don't think it resembles work-to-be-done.
