### ISSUE TITLE
'locale' is not a valid option at the mkdocs configuration level

### ISSUE THREAD

**Issue by Guts** [timvink/mkdocs-git-revision-date-localized-plugin#24]
According to the [README](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/tree/b6647efc74161682354992430fe609704193624a#locale), `locale` value can be set in two hierarchical ways:

1. `plugins/git-revision-date-localized` configuration
2. if not, fallback to the `theme` section

> When not set, this plugin will look for locale or language options set in your theme. If also not set, the fallback is English (en)

But in fact, the plugin is also looking for a locale option at the mkdocs level:

https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/b6647efc74161682354992430fe609704193624a/mkdocs_git_revision_date_localized_plugin/plugin.py#L41

Problem: this option is not an accepted one in [MkDocs configuration](https://www.mkdocs.org/user-guide/configuration/).

Sp, plugin should not look at this option.

**Comment by timvink** [comment]
Actually, this is done on purpose, as locale might be added to mkdocs in a future release. (Can't find the related issue now but have this from waylan himself)

**Comment by timvink** [comment]
Here is the [reference comment](https://github.com/squidfunk/mkdocs-material/issues/1350#issuecomment-559095892) from waylan, explaining `locale` might be part of mkdocs in the future.
