### ISSUE TITLE
Incompatibility with mkdocs-monorepo-plugin

### ISSUE THREAD

**Issue by pauloribeiro-codacy** [timvink/mkdocs-git-revision-date-localized-plugin#30]
Hello,

I'm opening this issue to let you know that [spotify/mkdocs-monorepo-plugin](https://github.com/spotify/mkdocs-monorepo-plugin) seems to be incompatible with this plugin. I opened an issue on their project:

https://github.com/spotify/mkdocs-monorepo-plugin/issues/12

**Comment by timvink** [comment]
Thanks for the heads-up! Seems like it is more an issue on their side (as you already identified, they copy the source files to a temp folder). I already commented with an idea for a solution.

I will leave this issue open for now, in case there is something that can be improved in this plugin to resolve this.

**Comment by pauloribeiro-codacy** [comment]
Thanks a lot, @timvink!

**Comment by timvink** [comment]
I have a MR to `mkdocs-monorepo-plugin` pending review that fixes this. 

No problem in this plugin so closing this issue as open issues should reflect work-to-be-done.
