### ISSUE TITLE
Support disabling on certain pages

### ISSUE THREAD

**Issue by RDIL** [timvink/mkdocs-git-revision-date-localized-plugin#43]
This would be nice as a front matter attribute or just an HTML comment, so that in cases such as a homepage, you aren't forced to have it.

**Comment by timvink** [comment]
I agree this would be nice to have!

Probably it makes sense to have an include/exclude options in the mkdocs.yml config. There are more plugins that offer this kind of tweaking. At the least, we could study the designs and copy the best one. `mkdocs` could also have the option to exclude certain pages from certain plugins, perhaps I'll open an issue and see if that would fit the design.

Pressed for time currently, but definitely this one is on the backlog. I'm also open to PR's of course.

**Comment by RDIL** [comment]
Opened a PR to fix.
