### ISSUE TITLE
source-date was renamed to source-file

### ISSUE THREAD

**Issue by elgalu** [timvink/mkdocs-git-revision-date-localized-plugin#53]
https://github.com/squidfunk/mkdocs-material/blob/409d1510440b3d1488a33213f12049a985161313/src/partials/source-date.html#L23-L24

**Comment by timvink** [comment]
Thanks for letting me know. I actually committed that line , see https://github.com/squidfunk/mkdocs-material/pull/2579.

I still reference to `source-date.html` in the docs (https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/master/docs/howto/override-a-theme.md), but this will be deprecated in `mkdocs-material v0.8`. I'll leave this issue open to make sure to update the docs page with the new partial.

**Comment by mrmanc** [comment]
Thanks for fixing this @timvink 😃
