### ISSUE TITLE
Not all pages show the revision date

### ISSUE THREAD

**Issue by aphive** [timvink/mkdocs-git-revision-date-localized-plugin#59]
Working on a local site for myself as well as an internal docs site at work. Both get random pages that don't show a last updated timestamp even when changes have been pushed to git and released to the actual docs site.

Sometimes the timestamp shows, but if I browse to a different page then come back, it's no longer there.

**Comment by timvink** [comment]
Fixed in [v0.9.3](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/releases/tag/v0.9.3) by @ErliSoares !
