### ISSUE TITLE
In material theme does not work with navigation.instant enabled

### ISSUE THREAD

**Issue by ErliSoares** [timvink/mkdocs-git-revision-date-localized-plugin#60]
https://squidfunk.github.io/mkdocs-material/reference/data-tables/#customization

Use only document$ in https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/9c6dd76ef567242425cecadcfd8ff3249f83da21/mkdocs_git_revision_date_localized_plugin/js/timeago_mkdocs_material.js#L3-L9
![image](https://user-images.githubusercontent.com/2334509/132006548-44724bbe-a387-4321-8544-67f0c0b9fdc9.png)

**Comment by timvink** [comment]
Fixed in [v0.9.3](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/releases/tag/v0.9.3) by @ErliSoares !
