### ISSUE TITLE
Get raw values, without HTML tags

### ISSUE THREAD

**Issue by ZsharE** [timvink/mkdocs-git-revision-date-localized-plugin#64]
Hi,

Is there any way to get the plain data value, without the HTML tag ?
Right know the `{{ page.meta.git_revision_date_localized }}` and `{{ page.meta.git_creation_date_localized }}` renders in a span tag.

```
<span class="git-revision-date-localized-plugin git-revision-date-localized-plugin-iso_date">2021-11-3</span>
```

There should be an option to be able to use only the date value.

I need this to be able to create custom meta tags for: `article:published_time` & `article:modified_time` properties like this:

```
<meta property="article:published_time" content="{{ page.meta.git_creation_date_localized }}">
<meta property="article:modified_time" content="{{ page.meta.git_revision_date_localized }}">
```

Thanks

**Comment by timvink** [comment]
Hi @ZsharE. Good point, I agree the raw date strings should be available for developers. Currently the span is hardcoded:

https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/ff73362e5be9250507ea8f8d6a22fa52124a7da3/mkdocs_git_revision_date_localized_plugin/util.py#L195-L200

I made some quick and dirty edits and exposed more date variants in `page.meta` (https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/commit/ff73362e5be9250507ea8f8d6a22fa52124a7da3). Just released in [0.10.1](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/releases/tag/v0.10.1). You can find the list of new available tags at https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/howto/override-a-theme/#custom-themes

**Comment by ZsharE** [comment]
Hi @timvink ,

Thanks for the quick release, but there's a little problem:

https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/master/mkdocs_git_revision_date_localized_plugin/plugin.py#L224

**is_first_commit** should be **True**.

**Comment by ZsharE** [comment]
Hi @timvink , any update about this issue ?

**Comment by timvink** [comment]
It's on my list but have had other stuff on my plate. Will prob look at it next Wednesday.

**Comment by ThomasArdal** [comment]
@timvink Sounds great. Let us know if we can help with anything. Test, etc.

**Comment by timvink** [comment]
Should be fixed now. I also spent a bit more time refactoring the code as `0.10.1`  introduced extra overhead due to extra `git log` operations.

Releases notes: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/releases/tag/v0.10.2

**Comment by ZsharE** [comment]
Everything works great now, thanks !
