### ISSUE TITLE
Fix fetch-depth

### ISSUE THREAD

**Issue by patrick-5546** [timvink/mkdocs-git-revision-date-localized-plugin#69]
**Context**
- GitHub action fix in the collapsible block: https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/index.html#note-when-using-build-environments

**Issue**
- Should be `fix-depth`, not `fix_depth`

**Evidence**
- Warning when running the workflow: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/actions/runs/1579704317

**Comment by timvink** [comment]
Thanks for reporting!

Would you like to create a PR ?

**Comment by patrick-5546** [comment]
Sure I can. I think I need permission to push my branch though.

**Comment by timvink** [comment]
You'll need to fork the repo to be able to create a PR.  See for example https://github.com/firstcontributions/first-contributions/blob/master/README.md.

Happy new year !

**Comment by patrick-5546** [comment]
Thanks for the help, and happy new year!
