### ISSUE TITLE
Newly created file: Python error when trying to get timestamp

### ISSUE THREAD

**Issue by christo-ph** [timvink/mkdocs-git-revision-date-localized-plugin#7]
This happens to a newly created md file, which is not yet under version control:

```
      File "/usr/local/lib/python3.7/site-packages/mkdocs_git_revision_date_localized_plugin/util.py", line 22, in get_revision_date_for_file
        unix_timestamp = int(self.g.log(path, n=1, date='short', format='%at'))
    ValueError: invalid literal for int() with base 10: ''
```

After a `git commit` mkdocs serve works as usual.

**Comment by timvink** [comment]
Thanks for letting me know! 

Released a new version, `pip install --upgrade mkdocs-git-revision-date-localized-plugin` should do the trick :)

**Comment by christo-ph** [comment]
Thanks for your quick response and fix. 

Works now.
