### ISSUE TITLE
README Dead Link Update

### ISSUE THREAD

**Issue by Rwarcards762** [timvink/mkdocs-git-revision-date-localized-plugin#71]
Hi, I noticed that the "Change your CI Settings" section has a dead link in relation to GitLab Runners (in reference to the `GIT_DEPTH` variable.)

The link should likely be updated to one of the following below:

- [Number of Changes to Fetch during Clone](https://docs.gitlab.com/ee/ci/pipelines/settings.html#limit-the-number-of-changes-fetched-during-clone)
- [Shallow Cloning: GIT_DEPTH](https://docs.gitlab.com/ee/ci/large_repositories/index.html#shallow-cloning)

This is something minor, but easy to fix and figured I would mention it. Thanks!

**Comment by timvink** [comment]
Thanks for letting me know! Would you like provide a PR? 

See https://opensource.com/article/19/7/create-pull-request-github in case you havent done this before.

**Comment by Rwarcards762** [comment]
Only comment -- it seems the `docs/index.md` pulls in `README.md` but hasn't been regenerated with the commit, causing it to still have an invalid link. I assume it can just wait until the next time the site is regenerated with a change :)
