### ISSUE TITLE
[Request] Introduce "enabled_if_env" option

### ISSUE THREAD

**Issue by BoxedBrain** [timvink/mkdocs-git-revision-date-localized-plugin#91]
Please introduce the "enabled_if_env" option as found in https://github.com/zhaoterryy/mkdocs-git-revision-date-plugin
This speeds up local testing and only uses the plugin in the CI pipeline.

Thanks!

**Comment by timvink** [comment]
Hi @BoxedBrain, does the `enabled` feature sufficiently cover your use case & can I close this issue?

**Comment by BoxedBrain** [comment]
Thanks @timvink for updating the docs! This solved my issue.
