### ISSUE TITLE
How to update git-revision-date-localized.json?

### ISSUE THREAD

**Issue by EDIflyer** [timvink/mkdocs-git-revision-date-localized-plugin#93]
Have been playing about with changing the display date based on the examples at https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/

I was a bit confused by the example first as custom date wasn't being displayed and there were VS Code errors in the schema check:
![image](https://user-images.githubusercontent.com/13610277/178502779-c8e32dbc-7ffa-4a7b-ad2e-9a9827d6be4e.png)

It turns out I had a to change the type to custom for it to make use of the custom format.  It looks like the schema needs a couple of additions, both to add `custom` to type and to recognise `custom_format` as a permissible variable.  I couldn't find it in the repo though so wasn't quite sure where to suggest changes?

**Comment by EDIflyer** [comment]
@timvink yes I spotted it mentioned here - https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration - works really well for catching issues before you save the `mkdocs.yml` file 😃 

![image](https://user-images.githubusercontent.com/13610277/178506624-da8ec01a-8fb5-4c7e-803e-cf4cdfc0c9c8.png)

**Comment by EDIflyer** [comment]
@squidfunk have created a PR to tweak the specific bits I found in case helpful!

**Comment by squidfunk** [comment]
I'd be happy to outsource maintenance of the plugin typings. When you finished the typings, we can switch to the typings provided by your repository [here](https://github.com/squidfunk/mkdocs-material/blob/9a594ee89f5f4ee8e3ed0e90d9b1c2df6acc3ab7/docs/schema/plugins.json#L65-L78) – just PR the URL hosting the JSON schema.

**Comment by timvink** [comment]
@EDIflyer thanks for the PR
@squidfunk I've moved `schema.json` to this repository, thanks for the pointer.
